language: go

go:
- 1.7.5
- 1.8rc3

env:
  global:
    - secure: "WCGl6fgiFfoGBPT2w8ER+izp9/zswvt2swuoGW4IBDQMT52KZRlx23oxabzud7/wZN6OJTHpfibcFQ1zvc/SL6UMzissxFSumCnIHqorf2IMMX6f0AX2AG8X9YaaQdKbWtcpeVASeTiezptTP/P9EvyvgvSAU0nSm4Lp1n989AFEQY70pRI3bI0PzjOhkzyYaFszBX78lMAueG9XSpNax29yFEEL43XsZhE+dDkQy79wtub+f/RyhsGaxs5gNpS0kx8ca1ihiITjst95kzqWM8kxmjayG3VXE9GaFBlMf961g0RPXipvaOaXJeo4OdOPleW6MulBIhm3BO+JNcFkLoRN3GV4JBmI0Usx3F0E+26S+Opw3h0wIWTFZZ3eq0zNrQFPiSe2zosDuUd52GHpL+pX620wTZdCGV8HWPchE9411KEHtZPTnNDOQKwk47W5k+2v5BL0J47U2FYUnyDwxmerlOy2QVsGzuUI+z7OyNgTPR/TprdMsdMkpc+o+1d7js12XVSYK/nAWd0qwemhd8gtYkpHt62bRqcJgrmQ3xTPhvWu82RbqGKn80k9kSYr5aV7v7jb+l2+k9SNBOO7v37G5pLFOxIwmXOZn+tY3DuXp+Qpxsi45Qw4ayKUeg/LFmiRuWO8LWq3CqOoMthxWONUPA9exqNEAATtb2qyA6g="
  matrix:
  - NAME=john
  - NAME=jane

before_deploy:
  - gem install fpm --no-document
  - make pkg
  - sed -i'' -e "s/\$VERSION/${TRAVIS_TAG:=0.0.0}/" descriptor.json
  - sed -i'' -e "s/\$DATE/$(date +%Y-%m-%d)/" descriptor.json

deploy:
  # "production" deploy
  - provider: bintray
    user: dominikznidar
    key: $BINTRAY_API_KEY
    file: descriptor.json
    skip_cleanup: true
    on:
      go: 1.7.5
      tags: true

  # "staging" deploy
  - provider: bintray
    user: dominikznidar
    key: $BINTRAY_API_KEY
    file: descriptor.json
    skip_cleanup: true
    on:
      go: 1.7.5
      branch: master
